version: '3'
services:
  db:
    container_name: db
    build:
      context: ./BackEnd/db_docker
      dockerfile: db.Dockerfile
    volumes:
      - db:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sept_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    networks:
      - my_network
  backend:
    build: ./BackEnd
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    networks:
      - my_network

  frontend:
    build: ./FrontEnd
    ports: 
     - 3000:3000
    stdin_open: true
    networks:
      - my_network

volumes:
   db: {}
networks:
  my_network:
    driver: bridge
